### ISSUE TITLE
Problem on linux with usb to serial 

### ISSUE THREAD

**Issue by EricMaiori** [yarrick/scsniff#2]
Hello freind All is working fine on a tradizional season  with serial port on board , but when we all tried to use it with a USB to Serial adapter TTL  it stuck on :
== Opened /dev/ttyUSB0
== Speed: 115200 baud
== Waiting for reset..
there is no way to make a reset ( with the classic season is simply we just plug the season on the reader and the log start ) .
When we try to unplug that come :+1: 
== Opened /dev/ttyUSB0
== Speed: 115200 baud
== Waiting for reset..  Done
Connection lost
On windows  is working fine and we dont need also to do plug  unplug , can you fix it ?
Thank you !

**Comment by yarrick** [comment]
It is hard to skip the reset since then the state machine will not be in the right state. I assume you got it working, let me know if the reset signal is using some other pin.
